### PR TITLE
Feature/stereotyped mappings

### PR DESCRIPTION
**Pull request by willem-xbreeze**
Add stereotype on datasource to enable using Mappings for different purposes besides MDDE modeling. For example when there is horizontal and vertical lineage defined in the model

### CODE REVIEW

**Comment by harmen-xb** [comment]
@willem-xbreeze I had a look at the changes, which seem ok this way.

I only thought you probably wanted to force the stereotype. Because things like model checks, form, etc. in the BaseClassifierMapping and BaseStructuralFeatureMapping metaclass (https://github.com/CrossBreezeNL/PowerDesigner-MDDE-Extension/tree/main/decomposed/extensions/MDDE_LDM/Profile/BaseClassifierMapping & https://github.com/CrossBreezeNL/PowerDesigner-MDDE-Extension/tree/feature/stereotyped_mappings/decomposed/extensions/MDDE_LDM/Profile/BaseStructuralFeatureMapping) should all also be moved into a Criterea on the DataSource stereotype. Right?

Otherwise all behavior modelling on the BaseClassifierMapping and BaseStructuralFeatureMapping will be applied to all mappings. Based on your story on being able to use mappings for different purposed won't work I think.

**Comment by willem-xbreeze** [comment]
> @willem-xbreeze I had a look at the changes, which seem ok this way.
> 
> I only thought you probably wanted to force the stereotype. Because things like model checks, form, etc. in the BaseClassifierMapping and BaseStructuralFeatureMapping metaclass (https://github.com/CrossBreezeNL/PowerDesigner-MDDE-Extension/tree/main/decomposed/extensions/MDDE_LDM/Profile/BaseClassifierMapping & https://github.com/CrossBreezeNL/PowerDesigner-MDDE-Extension/tree/feature/stereotyped_mappings/decomposed/extensions/MDDE_LDM/Profile/BaseStructuralFeatureMapping) should all also be moved into a Criterea on the DataSource stereotype. Right?
> 
> Otherwise all behavior modelling on the BaseClassifierMapping and BaseStructuralFeatureMapping will be applied to all mappings. Based on your story on being able to use mappings for different purposed won't work I think.

Latest checkin made the following changes:
- Moved all MDDE content in the extension under BaseClassifierMapping and BaseStructuralFeatureMapping to a new criterion. Note: This gives a lot of changes in Git which are only relocations of existing items in the extension
-  Changed the initialize event handler under BaseStructuralFeatureMapping (since event handlers cannot be moved under criterion) so it only runs on appropriate attribute mappings
- Made the export of mappings conditional, the MDDE XML export only includes MDDE mappings
- Added an example model with business concepts and a local extension in the ExampleDWH model to illustrate how this can work with an additional form for "business concept mappings"

**Review by harmen-xb — COMMENTED** [review]
The changes look fine, what I am missing is a change in the add new mapping method, where you would set the stereotype of the new data source to mdde_DataSource. Or how is this taken care of for new users of the extension that the stereotype is set on creation of the first mapping?

**Comment by willem-xbreeze** [comment]
> The changes look fine, what I am missing is a change in the add new mapping method, where you would set the stereotype of the new data source to mdde_DataSource. Or how is this taken care of for new users of the extension that the stereotype is set on creation of the first mapping?

The criterion allows datasource stereotype to be empty. But i have added a check now in the new mapping method to make sure that the datasource has a valid stereotype, either empty or mdde_datasource. See commit https://github.com/CrossBreezeNL/PowerDesigner-MDDE-Extension/pull/14/commits/5a269365f8d102aa46f54b66b6be73c27b70a535

**Review by harmen-xb — APPROVED** [review]
Changes look good to me.

**Pull request merged**
